package main

const defaultMode = "chaos-life"

var defaultModes = []string{defaultMode}

// 这些 ptr 开头的小函数是为了给可选字段生成指针。Go 的 int64 和 string 默认值分别是
// 0 和空字符串，但在接口数据里，“字段真的等于 0”和“字段不存在”是两件不同的事。
// 例如 MaxBuy 为空表示这个商品暂时没有购买次数上限，MaxBuy 等于 1 则表示最多出现一次。
// 用指针以后，结构体可以表达 nil，也就是“这个字段没有值”。JSON 输出时，前端就能区分
// null 和具体数字，后续接数据库时也更容易对应可空字段。
func ptrInt64(value int64) *int64 {
	return &value
}

func ptrString(value string) *string {
	return &value
}

func ptrDelta(value int64) *int64 {
	return &value
}

// bootstrapContent 返回一整局游戏开始前需要的内容包。现在它直接写在 Go 代码里，
// 这是早期联调用的最小方案：前端可以先通过 API 拿到商品、场景、事件、终局事件、
// 状态和音轨入口，不必等 PostgreSQL、迁移脚本和种子数据都完成。这里不是最终内容系统，后续内容稳定后，
// 这些样例数据应该迁移到数据库种子数据或独立内容文件，Go handler 只负责读取和返回。
func bootstrapContent() bootstrapResponse {
	initialBalance := defaultInitialBalance
	roundLimitMs := defaultRoundLimitMs

	return bootstrapResponse{
		Config: gameConfig{
			InitialBalance: initialBalance,
			RoundLimitMs:   roundLimitMs,
			DefaultMode:    defaultMode,
			BalanceTuning:  deriveBalanceTuning(initialBalance, roundLimitMs),
		},
		Items: []item{
			{
				ID:         "subway-extra-stop",
				Name:       "地铁坐过站补票",
				Category:   "找零小额",
				Price:      1,
				Tier:       "coin",
				Batchable:  true,
				Weight:     18,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"coin", "traffic", "daily"},
				Flavor:     "最后一元也要能花出去，离线兜底不能卡在个位余额。",
			},
			{
				ID:         "parking-half-hour",
				Name:       "停车半小时补费",
				Category:   "找零小额",
				Price:      68,
				Tier:       "small",
				Batchable:  true,
				Weight:     17,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"small", "traffic", "fee"},
				Flavor:     "不是大钱，但很适合测试十倍和二十倍的小额连刷。",
			},
			{
				ID:         "daily-breakfast-stack",
				Name:       "便利店早餐十连",
				Category:   "日常小额",
				Price:      180,
				Tier:       "daily",
				Batchable:  true,
				Weight:     16,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"daily", "batch"},
				Flavor:     "看起来便宜，刷起来很密。",
			},
			{
				ID:         "milk-tea-office",
				Name:       "奶茶全员请客",
				Category:   "社交压力",
				Price:      486,
				Tier:       "daily",
				Batchable:  true,
				Weight:     15,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"social", "drink"},
				Flavor:     "小额但高频，堆起来会很疼。",
			},
			{
				ID:         "ride-surge",
				Name:       "跨城打车溢价",
				Category:   "交通",
				Price:      1280,
				Tier:       "premium",
				Batchable:  true,
				Weight:     12,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"traffic", "surge"},
				Flavor:     "临时赶路，价格也临时起飞。",
			},
			{
				ID:         "concert-chain",
				Name:       "演唱会前排连锁",
				Category:   "娱乐",
				Price:      8860,
				Tier:       "large",
				Batchable:  true,
				Weight:     10,
				MinBalance: 8000,
				Modes:      defaultModes,
				Tags:       []string{"fun", "chain"},
				Flavor:     "票、酒店、车费一起入场。",
			},
			{
				ID:         "phone-replace",
				Name:       "手机碎屏换新",
				Category:   "数码意外",
				Price:      9999,
				Tier:       "large",
				Batchable:  false,
				Weight:     9,
				MinBalance: 5000,
				Modes:      defaultModes,
				Tags:       []string{"repair", "digital"},
				Flavor:     "维修报价让人直接换新。",
			},
			{
				ID:         "pet-emergency",
				Name:       "宠物急诊押金",
				Category:   "宠物",
				Price:      16800,
				Tier:       "large",
				Batchable:  false,
				Weight:     8,
				MinBalance: 10000,
				Modes:      defaultModes,
				Tags:       []string{"pet", "medical"},
				Flavor:     "不做医学建议，只做账单提醒。",
			},
			{
				ID:         "renovation-rework",
				Name:       "装修返工增项",
				Category:   "大件现实",
				Price:      68000,
				Tier:       "heavy",
				Batchable:  false,
				Weight:     7,
				MinBalance: 40000,
				Modes:      defaultModes,
				Tags:       []string{"renovation", "rework"},
				Flavor:     "敲开墙，也敲开预算。",
			},
			{
				ID:         "auction-mistap",
				Name:       "拍卖误举牌",
				Category:   "高端误操作",
				SceneID:    ptrString("auction-night"),
				Price:      188000,
				Tier:       "shock",
				MaxBuy:     ptrInt64(1),
				Batchable:  false,
				Weight:     4,
				MinBalance: 120000,
				Modes:      defaultModes,
				Tags:       []string{"auction", "mistap"},
				Flavor:     "手举起来，钱落下去。",
			},
			{
				ID:         "yacht-cleaning",
				Name:       "游艇清洁赔补",
				Category:   "富人体验",
				SceneID:    ptrString("masked-party"),
				Price:      96000,
				Tier:       "heavy",
				MaxBuy:     ptrInt64(1),
				Batchable:  false,
				Weight:     5,
				MinBalance: 80000,
				Modes:      defaultModes,
				Tags:       []string{"luxury", "service-fee"},
				Flavor:     "租赁没买贵，服务费贵。",
			},
			{
				ID:         "castle-deposit",
				Name:       "古堡酒店定金",
				Category:   "富人体验",
				SceneID:    ptrString("masked-party"),
				Price:      128000,
				Tier:       "shock",
				MaxBuy:     ptrInt64(1),
				Batchable:  false,
				Weight:     4,
				MinBalance: 100000,
				Modes:      defaultModes,
				Tags:       []string{"luxury", "deposit"},
				Flavor:     "住不起没关系，定金先行。",
			},
			{
				ID:         "tax-refund",
				Name:       "退税突然到账",
				Category:   "反向进账",
				Price:      22000,
				Tier:       "income",
				Batchable:  false,
				Weight:     6,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"income", "refund"},
				Flavor:     "不是奖励，是阻碍清空。",
			},
			{
				ID:         "hotel-compensation",
				Name:       "酒店超售赔付",
				Category:   "赔付",
				Price:      8000,
				Tier:       "income",
				Batchable:  false,
				Weight:     7,
				MinBalance: 0,
				Modes:      defaultModes,
				Tags:       []string{"income", "compensation"},
				Flavor:     "钱回来了，通关远了。",
			},
		},
		Scenes: []scene{
			{
				ID:          "daily-loop",
				Name:        "工作日循环",
				EntryCost:   0,
				DurationSec: 35,
				MinBalance:  0,
				Rarity:      "common",
				RiskLevel:   2,
				ItemTags:    []string{"daily", "traffic", "social"},
				EventTags:   []string{"refund", "surge"},
				Modes:       defaultModes,
			},
			{
				ID:          "auction-night",
				Name:        "拍卖预展",
				EntryCost:   12000,
				DurationSec: 35,
				MinBalance:  120000,
				Rarity:      "wild",
				RiskLevel:   5,
				ItemTags:    []string{"auction", "luxury"},
				EventTags:   []string{"mistap"},
				Modes:       defaultModes,
			},
			{
				ID:          "masked-party",
				Name:        "面具舞会",
				EntryCost:   18000,
				DurationSec: 35,
				MinBalance:  80000,
				Rarity:      "rare",
				RiskLevel:   4,
				ItemTags:    []string{"luxury", "deposit", "service-fee"},
				EventTags:   []string{"compensation", "fee"},
				Modes:       defaultModes,
			},
		},
		Events: []gameEvent{
			{
				ID:            "refund-sting",
				Title:         "反向进账",
				Description:   "退款到账，清空进度被拖回。",
				Delta:         ptrDelta(8000),
				Probability:   0.12,
				CooldownSec:   8,
				Tags:          []string{"income", "refund"},
				Modes:         defaultModes,
				SettlementTag: "最烦人返钱",
			},
			{
				ID:            "rush-fee",
				Title:         "加急服务费",
				Description:   "高压状态下追加服务费。",
				Delta:         ptrDelta(-12000),
				Probability:   0.16,
				CooldownSec:   6,
				Tags:          []string{"fee", "rush"},
				Modes:         defaultModes,
				SettlementTag: "最荒诞扣款",
			},
		},
		Endings: []terminalEvent{
			{
				ID:            "heart-alarm-blackout",
				Title:         "心脏报警停表",
				Description:   "系统提示你先离开收银台处理身体报警。本局提前停表，只记录账单，不提供医学建议。",
				Probability:   0.0005,
				MinElapsedMs:  240000,
				MinRiskLevel:  4,
				BalanceEffect: "none",
				Tags:          []string{"medical", "health", "ending"},
				Modes:         defaultModes,
				SettlementTag: "心脏报警终局",
			},
			{
				ID:            "bankruptcy-zero",
				Title:         "破产式清零",
				Description:   "一连串费用把剩余额度直接归零。主线目标达成，但结算会标记为特殊终局。",
				Probability:   0.0007,
				MinElapsedMs:  300000,
				MaxBalance:    ptrInt64(280000),
				MinRiskLevel:  3,
				BalanceEffect: "zero",
				Tags:          []string{"fee", "legal", "late-fee", "ending"},
				Modes:         defaultModes,
				SettlementTag: "破产式清零",
			},
		},
		Statuses: []statusEffect{
			{
				ID:                    "rage-buy",
				Name:                  "生气",
				DurationSec:           12,
				ItemRefreshMultiplier: 1.15,
				HighPriceMultiplier:   1.3,
				EventMultiplier:       1.1,
				Tags:                  []string{"impulse", "auction", "high-risk", "big-spend"},
				Description:           "高价消费更容易出现。",
			},
			{
				ID:                    "low-mood",
				Name:                  "低落",
				DurationSec:           14,
				ItemRefreshMultiplier: 0.8,
				HighPriceMultiplier:   0.9,
				EventMultiplier:       1.05,
				Tags:                  []string{"low-mood", "daily", "income", "refund", "low-balance"},
				Description:           "刷新变慢，限时高压场景会临时退回普通货架。",
			},
			{
				ID:                    "hype-spree",
				Name:                  "上头",
				DurationSec:           10,
				ItemRefreshMultiplier: 1.25,
				HighPriceMultiplier:   1.35,
				EventMultiplier:       1.2,
				Tags:                  []string{"impulse", "mistap", "platform", "high-risk", "rush"},
				Description:           "批量和误操作风险上升，货架节奏变得更急。",
			},
			{
				ID:                    "lucky-backfire",
				Name:                  "好运",
				DurationSec:           10,
				ItemRefreshMultiplier: 1,
				HighPriceMultiplier:   0.8,
				EventMultiplier:       1.4,
				Tags:                  []string{"income", "refund", "compensation", "income-scene"},
				Description:           "返钱和赔付更容易出现。",
			},
		},
		AudioTracks: []audioTrack{
			{
				ID:        "rush",
				Title:     "内置合成收银循环",
				Mood:      "rush",
				Src:       "",
				License:   "custom",
				SourceURL: "",
			},
			{
				ID:        "danger",
				Title:     "内置合成高压循环",
				Mood:      "danger",
				Src:       "",
				License:   "custom",
				SourceURL: "",
			},
			{
				ID:        "settlement",
				Title:     "内置合成结算循环",
				Mood:      "settlement",
				Src:       "",
				License:   "custom",
				SourceURL: "",
			},
		},
	}
}
